[server]
enableCORS = true
enableXsrfProtection = false
port = 8501
maxUploadSize = 500
maxMessageSize = 500

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#64ffda"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "debug"
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"
