# API Keys
GEMINI_API_KEY = "AIzaSyD0ob8GO26DNiK0e3wgd0u5deOTdK37_ig"

# Project 1 Configuration
[project1]
api_key = "AIzaSyD0ob8GO26DNiK0e3wgd0u5deOTdK37_ig"

# Project 2 Configuration
[project2]
gemini_api_keys = [
    "AIzaSyB84IDnLHw695xY3LSruiHvW3e18QE-q-A",
    "AIzaSyBBTgtN0FIKccxJLGRzmUkKhPQRT3xcCK8",
    "AIzaSyDbfmgqkIZ_NnZI3OajDDUpjvgHXaFqb6E",
    "AIzaSyAFv6bTyHrjHVhLzrK867mVzqbTwBx73JE",
    "AIzaSyCGfzbsdEzLscQD-fN2wZ3aAZJ52LLWHzc"
]

# API Configuration
[api_config]
base_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
timeout = 30
max_retries = 3
cooldown_period = 600
max_failures = 3

# Security Configuration
[security_config]
allowed_origins = ["http://localhost:8501"]
rate_limit_requests_per_minute = 60
rate_limit_burst = 10 
